### ISSUE TITLE
Firestore Extension No Longer Working

### ISSUE THREAD

**Issue by rsun11** [algolia/firestore-algolia-search#204]
My guess is that an update was made last night in Firebase Cloud Functions to not allow Gen 1 triggers on a named firestore database.

- Install the Algolia Firestore Extension with a non-default database id
- The extension will show this installation error "...Triggers must be created with a \"(default)\" Firestore Native database. See https://firebase.google.com/docs/firestore/extend-with-functions#limitations."

So this line in extension.yaml doesn't seem to be supported anymore.

> resources:
>   \- name: executeIndexOperation
>     type: firebaseextensions.v1beta.function
>     description: >-
>       Firestore document-triggered function that creates, updates, or deletes data in Algolia.
>     properties: # LOCATION is a user-configured parameter value specified by the user
>       \# during installation.
>       location: ${LOCATION}
>       runtime: nodejs18
>       eventTrigger:
>         eventType: providers/cloud.firestore/eventTypes/document.write
>         resource:  #projects/${PROJECT_ID}/databases/${DATABASE_ID}/documents/${COLLECTION_PATH}/{documentID}

The fix looks to be a conversion to a gen 2 trigger: #169

**Comment by smomin** [comment]
@rsun11 if you have the time to create a PR, I can review it.  I am going to do some investigation on this.

**Comment by rsun11** [comment]
Tried deploying the same code to a gen 2 trigger but the database context is referencing the default database so “exists” property always returned false and calls to the named database throws an exception.

**Comment by smomin** [comment]
@rsun11 can you share your configuration?  the Firebase team has not heard of this issue so they are wondering if the extension was misconfigured.

**Comment by rsun11** [comment]
entered:
- extension instance ID: nucleus-70fd6e56-973f-4436-b650-dc308ddc9b2a
- Database ID: nucleus-70fd6e56-973f-4436-b650-dc308ddc9b2a
- collection path: products
- Force Data Sync: no
- algolia index name
- algolia application id
- full index existing documents: false
- cloud functions location: us-west3

Tried again this morning and the same issue is happening...

Finally got the trigger to work with:

`export const executeIndexOperation = onDocumentWritten(
  {
    document: 'documents/{documentId}',
    database: DATABASEID,
    region: REGION,
  },
  async (change): Promise<void> => {`

but this only works when deployed using the firebase cli.
- if you manually create a new gen 2 trigger with the code above, a byte array is passed to the function
- if you deploy the trigger with gcloud cli, a byte array is passed to the function
the byte array will need to be processed like this: https://cloud.google.com/functions/docs/calling/cloud-firestore

**Comment by rsun11** [comment]
Also, executeFullIndexOperation wasn't working with a named database. The query would always return results from the default database. Had to update to:
```
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.8.2",
```
for it to start working again.

**Comment by smomin** [comment]
hey @rsun11 I am going through the updates you mentioned here.  I am also talking to the Firebase team which seems surprised that I had this working in gen1 before some update that broke it.  will let you know what happens.

**Comment by rsun11** [comment]
One thing to try would be to deploy the current code as a gen 2 trigger but with the firebase package updates from above.

**Comment by smomin** [comment]
hey @rsun11 

I tried implementing you suggestions.  using the CLI deploy the update code, fails with this error message: 

```
- update firestore-algolia-search-s4eg
; RESOURCE_ERROR at /deployments/firebase-ext-firestore-algolia-search-s4eg/resources/executeIndexOperation: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Cannot create Firestore trigger for projects/algolia-store/databases/test. Triggers must be created with a \"(default)\" Firestore Native database. See https://firebase.google.com/docs/firestore/extend-with-functions#limitations."}

```

What steps did you take to implement gen2 versions for the extension.

**Comment by rsun11** [comment]
If you change the function to

`export const executeIndexOperation = onDocumentWritten( { document: 'documents/{documentId}', database: DATABASEID, region: REGION, }, async (change): Promise<void> => { `

the deployment will detect the signature as gen 2. I don’t think DatabaseId and region could not be stored as environment variables since the deployment needs those values populated during deployment to create the trigger.

**Comment by smomin** [comment]
hey @rsun11 I am working with the firebase team to see if we can get this resolved.  No eta at the moment.

**Comment by smomin** [comment]
hey @rsun11 is this still an issue?

**Comment by rsun11** [comment]
Not sure. I've deployed the code manually through the cli so haven't used
the extension in a while.

**Comment by smomin** [comment]
Update: Firebase team has mentioned that they will be support named database to be configured with the Firebase extension.  Once they do officially support it, I will take a look at it.

**Comment by jayman2989** [comment]
Just checking in to state that this IS still an issue. I have named databases configured in my algolia extensions (3 of them, dev, stage, and prod). We recently moved to named DBs in firestore, and Algolia is very unreliable about reading the documents from them. I consistently see logs of it attempting to read from the default DB instead of the named DB.

`Error when performing Algolia index Error: 3 INVALID_ARGUMENT: The request was for database 'projects/project-id-here/databases/(default)' but was attempting to access database 'projects/project-id-here/databases/development'`

**Comment by mesrobk** [comment]
> Just checking in to state that this IS still an issue. I have named databases configured in my algolia extensions (3 of them, dev, stage, and prod). We recently moved to named DBs in firestore, and Algolia is very unreliable about reading the documents from them. I consistently see logs of it attempting to read from the default DB instead of the named DB.
> 
> `Error when performing Algolia index Error: 3 INVALID_ARGUMENT: The request was for database 'projects/project-id-here/databases/(default)' but was attempting to access database 'projects/project-id-here/databases/development'`

I was also receiving this error. I realized setting the Force Data Sync to 'No' does mitigate the issue. Still a problem with the extension but a descent workaround.
